#!/bin/zsh

# Location of the script i.e. of the dotfiles themselves
dotfile_path=${0:a:h}
echo "Dotfile path is: $dotfile_path"

# Parameter order as in ln, $1 is target and $2 is the link name
lndotfile() {
  if [ -f $2 ]; then
    rm $2
  fi
  ln -s -- "$1" "$2"
}

# Get submodules
git submodule init
git submodule update

# Install oh-my-zsh non-intrusively
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# Install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Link dotfiles
lndotfile "$dotfile_path/.zshrc" "$HOME/.zshrc"
lndotfile "$dotfile_path/.zshrc.aliases" "$HOME/.zshrc.aliases"
lndotfile "$dotfile_path/.zshrc.functions" "$HOME/.zshrc.functions"
lndotfile "$dotfile_path/.p10k.zsh" "$HOME/.p10k.zsh"
lndotfile "$dotfile_path/.fzf.zsh" "$HOME/.fzf.zsh"

# Install rust/cargo locally, -y for default options
curl https://sh.rustup.rs -sSf | sh -s -- -y 
source $HOME/.cargo/env

# Install zoxide - workaround since normal installation doesn't work on Raspberry Pi
# curl https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh --output install_zoxide.sh
# chmod +x install_zoxide.sh
# ./install_zoxide.sh
# rm install_zoxide.sh
cargo install zoxide

# Install fd-find
cargo install fd-find

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/.fzf"
"$HOME/.fzf/install" --bin
