#!/bin/zsh

# Parameter order as in ln, $1 is target and $2 is the link name
lndotfile() {
  if [ -f $2 ]; then
    rm $2
  fi
  ln -s -- "$1" "$2"
}

# Get submodules
git submodule init
git submodule update

# Install oh-my-zsh non-intrusively
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# Install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Link dotfiles
lndotfile "$HOME/.dotfiles/.zshrc" "$HOME/.zshrc"
lndotfile "$HOME/.dotfiles/.zshrc.aliases" "$HOME/.zshrc.aliases"
lndotfile "$HOME/.dotfiles/.zshrc.functions" "$HOME/.zshrc.functions"
lndotfile "$HOME/.dotfiles/.p10k.zsh" "$HOME/.p10k.zsh"

# Install zoxide
curl -s https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest | grep "browser_download_url" | cut -d '"' -f 4 | grep "x86_64-unknown-linux-musl" | xargs -n 1 curl -LJO
mkdir -p "$HOME/.local/bin"
mv "zoxide-x86_64-unknown-linux-musl" "$HOME/.local/bin/zoxide"
chmod +x "$HOME/.local/bin/zoxide"

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git fzf
fzf/install
